[project]
name = "roll-table-cli"
version = "0.1.0"
authors = [{ name = "Anderson Kagel", email = "Anderson.Kagel@gmail.com" }]
requires-python = ">=3.11"
dependencies = ["roll-table>=0.1.0"]

[tool.uv.sources]
roll-table = { workspace = true }

[project.scripts]
roll-table = "roll_table_cli:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
